services:
    php-fpm:
        build: ./docker
        image: phpish:1.1.2
        volumes:
            - .:/var/www/html
        networks:
            - mainnet
    nginx:
        image: nginx:1.27-alpine
        restart: unless-stopped
        volumes:
            - .:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        networks:
            - mainnet
        depends_on:
            - php-fpm

networks:
    mainnet:
